[[redirects]]
  from = "/api/v1/*"
  to = "https://data.renfe.com/api/3/action/datastore_search"
  status = 200

[[redirects]]
  from = "/api/v2/*"
  to = "https://horarios.renfe.com/cer/HorariosServlet"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200